development:
  adapter: postgresql
  encoding: utf8
  database: crm_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: crm_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: crm_production
  pool: 5